/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ArbolBinario;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author chiza
 */
public class ArbolFrm extends javax.swing.JFrame {

    /**
     * Creates new form ArbolFrm
     */
    ArbolBinario arbol = new ArbolBinario();

    public ArbolFrm() {
        initComponents();

        arbol.cargarDesdeArchivo("/home/chiza/NetBeansProjects/Arboles/src/ArbolBinario/datos.txt");

        // Configura el JPanel con el árbol binario
        ArbolPanel panelDibujo = new ArbolPanel(arbol);
        arbolPanel.setLayout(new BorderLayout());
        arbolPanel.add(panelDibujo, BorderLayout.CENTER);
        arbolPanel.revalidate();
        arbolPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        arbolPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtValorBus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPre = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        btnPost = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        background.setMaximumSize(new java.awt.Dimension(800, 600));
        background.setMinimumSize(new java.awt.Dimension(800, 600));
        background.setPreferredSize(new java.awt.Dimension(800, 600));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        arbolPanel.setBackground(new java.awt.Color(204, 255, 0));

        javax.swing.GroupLayout arbolPanelLayout = new javax.swing.GroupLayout(arbolPanel);
        arbolPanel.setLayout(arbolPanelLayout);
        arbolPanelLayout.setHorizontalGroup(
            arbolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        arbolPanelLayout.setVerticalGroup(
            arbolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        background.add(arbolPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 580));

        jLabel1.setText("Valor: ");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));
        background.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 130, -1));

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        background.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 40, 170, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        background.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 170, -1));
        background.add(txtValorBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 130, -1));

        jLabel2.setText("Valor: ");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        btnPre.setText("Pre-Orden");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });
        background.add(btnPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 170, 30));

        btnIn.setText("In-Orden");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });
        background.add(btnIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 170, 30));

        btnPost.setText("Post-Orden");
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostActionPerformed(evt);
            }
        });
        background.add(btnPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 170, 30));

        jLabel3.setText("Recorridos");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 170, -1));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 190, 10));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 190, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if (txtValor.getText() == null) {
            System.out.println("Ingrese un valor");
        } else {
            arbol.cargarDesdeArchivo("/home/chiza/NetBeansProjects/Arboles/src/ArbolBinario/datos.txt");
            arbol.insertar(Integer.parseInt(txtValor.getText()));
            arbolPanel.repaint();
        }
        txtValor.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        ArbolPanel panelDibujo = (ArbolPanel) arbolPanel.getComponent(0);
        panelDibujo.iniciarAnimacionRecorrido("preorden");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        ArbolPanel panelDibujo = (ArbolPanel) arbolPanel.getComponent(0);
        panelDibujo.iniciarAnimacionRecorrido("inorden");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInActionPerformed

    private void btnPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostActionPerformed
        ArbolPanel panelDibujo = (ArbolPanel) arbolPanel.getComponent(0);
        panelDibujo.iniciarAnimacionRecorrido("postorden");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPostActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            // Obtener el valor ingresado por el usuario
            int valor = Integer.parseInt(txtValorBus.getText());

            // Obtener el panel de dibujo y realizar la búsqueda
            ArbolPanel panelDibujo = (ArbolPanel) arbolPanel.getComponent(0);
            panelDibujo.buscarNodoConPopUp(valor);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        txtValorBus.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arbolPanel;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnPost;
    private javax.swing.JButton btnPre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorBus;
    // End of variables declaration//GEN-END:variables
}
